CREATE TABLE IF NOT EXISTS temporary_uploads (
  id VARCHAR(64) NOT NULL,
  temporary_file_id VARCHAR(64) NOT NULL,
  storage_key VARCHAR(255) NOT NULL,
  original_file_name VARCHAR(255) NOT NULL,
  physical_file_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(255) NOT NULL,
  extension VARCHAR(64) NOT NULL,
  file_size BIGINT UNSIGNED NOT NULL,
  checksum VARCHAR(255) NULL,
  uploaded_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  expires_at DATETIME(3) NOT NULL,
  consumed_at DATETIME(3) NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_temporary_uploads_temporary_file_id (temporary_file_id),
  UNIQUE KEY uq_temporary_uploads_storage_key (storage_key),
  KEY idx_temporary_uploads_expires_at (expires_at),
  KEY idx_temporary_uploads_consumed_at (consumed_at),
  KEY idx_temporary_uploads_created_by_user_id (created_by_user_id),
  CONSTRAINT fk_temporary_uploads_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
